# Generated by Django 6.0 on 2026-01-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('channel_name', models.CharField(db_index=True, max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('delivered', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_index=True)),
                ('channel_name', models.CharField()),
                ('expires_at', models.DateTimeField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['group_name', 'joined_at'], name='channels_db_group_n_3426ab_idx')],
                'unique_together': {('group_name', 'channel_name')},
            },
        ),
    ]
