# Generated by Django 6.0 on 2026-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_lite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='channels_li_channel_45ccc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupmembership',
            name='channels_li_group_n_78f885_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group_name',
            field=models.CharField(),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['channel_name', 'delivered', 'expires_at'], name='channels_li_channel_7553e7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group_name', 'expires_at'], name='channels_li_group_n_6c3675_idx'),
        ),
    ]
