# Generated by Django 6.0 on 2026-01-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_lite', '0002_remove_event_channels_li_channel_45ccc8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.BinaryField(),
        ),
    ]
